import { useEffect, useState, type FormEvent } from "react";
import { ArrowRight, Check, Eye, EyeOff, LockKeyhole } from "lucide-react";
import type { Translate } from "./model";

export function PasswordResetForm({ t, onCancel }: { t: Translate; onCancel?: () => void }) {
  const [ready, setReady] = useState(false), [password, setPassword] = useState(""), [confirm, setConfirm] = useState(""), [show, setShow] = useState(false), [error, setError] = useState(""), [done, setDone] = useState(false);
  useEffect(() => setReady(true), []);
  function submit(e: FormEvent) { e.preventDefault(); if (password.length < 12 || password !== confirm) { setError(t("Use at least 12 characters and enter the same password in both fields.", "استخدم 12 حرفًا على الأقل وأدخل كلمة المرور نفسها في الحقلين.")); return; } setError(""); setPassword(""); setConfirm(""); setDone(true); }
  if (done) return <div className="ws-success" tabIndex={-1} role="status"><Check size={30} /><h3>{t("Preview complete.", "اكتملت المعاينة.")}</h3><p>{t("Password validation passed. No password was sent or saved. A live recovery session is required to update an account.", "اجتازت كلمة المرور التحقق. لم تُرسل أو تُحفظ. يلزم رابط استعادة فعلي لتحديث الحساب.")}</p><button className="ws-button secondary" type="button" onClick={() => setDone(false)}>{t("Back to form", "العودة إلى النموذج")}<ArrowRight size={17} /></button></div>;
  return <form onSubmit={submit}><fieldset disabled={!ready}><p>{t("Use at least 12 characters. Choose a password you haven’t used elsewhere.", "استخدم 12 حرفًا على الأقل وكلمة مرور لم تستخدمها في مكان آخر.")}</p><label className="ws-field">{t("New password", "كلمة المرور الجديدة")}<div className="ws-password"><input required type={show ? "text" : "password"} minLength={12} maxLength={128} autoComplete="new-password" value={password} onChange={(e) => { setPassword(e.target.value); setError(""); }} /><button type="button" className="ws-icon" onClick={() => setShow(!show)} aria-label={show ? t("Hide password", "إخفاء كلمة المرور") : t("Show password", "إظهار كلمة المرور")}>{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label><label className="ws-field">{t("Confirm new password", "تأكيد كلمة المرور الجديدة")}<input required minLength={12} maxLength={128} type={show ? "text" : "password"} autoComplete="new-password" value={confirm} onChange={(e) => { setConfirm(e.target.value); setError(""); }} /></label>{error && <p className="ws-error" role="alert">{error}</p>}<div className="ws-form-actions"><button className="ws-button" type="submit"><LockKeyhole size={17} />{t("Preview password reset", "معاينة إعادة التعيين")}<ArrowRight size={17} /></button>{onCancel && <button className="ws-button secondary" type="button" onClick={onCancel}>{t("Cancel", "إلغاء")}</button>}</div><p className="ws-form-note">{t("Design preview. No credentials are sent or stored.", "معاينة تصميم. لا تُرسل بيانات تسجيل الدخول أو تُحفظ.")}</p></fieldset></form>;
}
